"""change email to username"""

revision = 'd1b581a0817d'
down_revision = '821be1fd510a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('persons', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('persons', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('recognition_logs', sa.Column('mood', sa.String(length=20), nullable=True))
    op.add_column('recognition_logs', sa.Column('liveness_score', sa.Float(), nullable=True))
    op.add_column('recognition_logs', sa.Column('tracking_id', sa.Integer(), nullable=True))
    op.add_column('recognition_logs', sa.Column('is_enhanced', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_unknown_face_logs_cluster_id'), 'unknown_face_logs', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_unknown_face_logs_embedding_hash'), 'unknown_face_logs', ['embedding_hash'], unique=False)
    op.create_index(op.f('ix_unknown_face_logs_is_reviewed'), 'unknown_face_logs', ['is_reviewed'], unique=False)
    op.create_index(op.f('ix_unknown_face_logs_timestamp'), 'unknown_face_logs', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_unknown_face_logs_timestamp'), table_name='unknown_face_logs')
    op.drop_index(op.f('ix_unknown_face_logs_is_reviewed'), table_name='unknown_face_logs')
    op.drop_index(op.f('ix_unknown_face_logs_embedding_hash'), table_name='unknown_face_logs')
    op.drop_index(op.f('ix_unknown_face_logs_cluster_id'), table_name='unknown_face_logs')
    op.drop_column('recognition_logs', 'is_enhanced')
    op.drop_column('recognition_logs', 'tracking_id')
    op.drop_column('recognition_logs', 'liveness_score')
    op.drop_column('recognition_logs', 'mood')
    op.drop_column('persons', 'tags')
    op.drop_column('persons', 'gender')
    op.drop_column('persons', 'age')
    # ### end Alembic commands ###
